name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

env:
  CSV_URL: "./project/water_potability_preprocessing.csv"
  TARGET_VAR: "Potability"
  MLFLOW_TRACKING_URI: "https://dagshub.com/Sulbae/Latihan-MLFlow.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagshub "mlflow>=2,<3" pandas numpy scikit-learn
      
      # Run Training
      - name: Run training script
        id: train_model
        run: |
          python modelling_tuning.py | tee output.log

          # Ambil BEST_MODEL_URI dari output
          BEST_URI=$(grep "REGISTERED_MODEL_NAME" output.log | sed 's/.*REGISTERED_MODEL_NAME: //')
          echo "MODEL_NAME=$MODEL_NAME" >> $GITHUB_ENV
          echo "Model Registered Name: $MODEL_NAME"
      
      - name: Validate MODEL_NAME
        run: |
          if [ -z "${{ env.MODEL_NAME }}" ]; then
            echo "ERROR: MODEL_NAME tidak ditemukan dari training!"
            exit 1
          fi
          
      # Build Docker Image
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --build-arg MODEL_NAME=${{ env.MODEL_NAME }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/potability-model:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/potability-model:latest
      
      # Inference
      - name: Run inference test
        run: python inference.py
        env:
          MODEL_NAME: ${{ env.MODEL_NAME }}
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}