name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env: 
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_ARTIFACT_URI: ./project/mlruns

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"
      
      # Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.12"
          use-mamba: true
          activate-environment: "mlflow-env"
          environment-file: project/conda.yaml
          auto-activate-base: false
      
      # Clear Env
      - name: Clear MLflow Environment Vars
        run: |
          unset MLFLOW_RUN_ID || true
          unset MLFLOW_EXPERIMENT_ID || true
      
      # Run MLflow Training
      - name: Run MLflow Project
        id: training
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate mlflow-env
          
          pip install -q dagshub 'mlflow==2.22.0' scikit-learn pandas numpy setuptools wheel

          OUTPUT=$(cd project && mlflow run . -e train_tuning --env-manager=local -P experiment_name="Random Forest_Grid Search")

          RUN_ID=$(echo "$OUTPUT" | grep 'RUN ID:' | tail -1 | awk '{print $3}')

          echo "Run output:"
          echo "$OUTPUT"

          if [ -z "$RUN_ID" ]; then
            echo "::error::ERROR: Gagal mengekstrak Run ID dari output pelatihan. Cek log output di atas."
            exit 1
          fi

          echo "Run ID successfully extracted: $RUN_ID"
          
          # Simpan Run ID ke variabel output GitHub Actions
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # Save artifact ke GitHub
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: project/mlruns

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker Image from model registry
      - name: MLflow Build Docker Image
        shell: bash -l {0}
        run: |
          RUN_ID="${{ steps.training.outputs.run_id }}"

          echo "Building Docker for Model Run ID: $RUN_ID"
          
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/best_model" \
            --name ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest