name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    env: 
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"

      # Install MLflow
      - name: Install dependencies
        run: |
          pip install mlflow==2.14 scikit-learn pandas numpy

      # Run MLflow Training
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -e train_tuning

      # Save artifact ke GitHub
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: project/mlruns

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker Image from model registry
      - name: MLflow Build Docker Image
        run: |
          mlflow models build-docker \
            --model-uri "models:/water_potability_v1/1" \
            --build-image-name ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest