name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

env:
  CSV_URL: "./project/water_potability_preprocessing.csv"
  TARGET_VAR: "Potability"
  MLFLOW_TRACKING_URI: "https://dagshub.com/Sulbae/Latihan-MLFlow.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagshub "mlflow>=2,<3" pandas numpy scikit-learn
      
      # Run Training
      - name: Run training script
        id: train_model
        run: |
          python modelling_tuning.py | tee output.log

          # Ambil BEST_MODEL_URI dari output
          BEST_URI=$(grep "BEST_MODEL_URI" output.log | sed 's/.*BEST_MODEL_URI: //')
          echo "MODEL_URI=$BEST_URI" >> $GITHUB_ENV
          echo "Model URI: $BEST_URI"
      
      - name: Validate MODEL_URI
        run: |
          if [ -z "${{ env.MODEL_URI }}" ]; then
            echo "ERROR: MODEL_URI tidak ditemukan dari training!"
            exit 1
          fi

      # Get from DagsHub                
      - name: Authenticate to DagsHub
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.DAGSHUB_USERNAME }}:${{ secrets.DAGSHUB_TOKEN }}@dagshub.com" > ~/.git-credentials
      
      - name: Download best model from DagsHub
        run: |
          mkdir -p model
          mlflow artifacts download \
            --artifact-uri "${{ env.MODEL_URI }}" \
            --dst-path model/
          
          echo "Downloaded model artifacts:"
          ls -R model
          
      # Build Docker Image
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/potability-model:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/potability-model:latest
      
      # Inference
      - name: Run inference test
        run: python inference.py
        env:
          MODEL_URI: ${{ env.MODEL_URI }}