name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env: 
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"
      
      # Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.12"
          use-mamba: true
          activate-environment: "mlflow-env"
          environment-file: project/conda.yaml
          auto-activate-base: false
      
      # Clear Env
      - name: Clear MLflow Environment Vars
        run: |
          unset MLFLOW_RUN_ID || true
          unset MLFLOW_EXPERIMENT_ID || true
      
      # Run MLflow Training
      - name: Run MLflow Project
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate mlflow-env
          
          pip install -q dagshub 'mlflow>=2,<3' scikit-learn pandas numpy setuptools wheel

          cd project
          mlflow run . -e train_tuning --env-manager=local -P experiment_name="Random Forest_Grid Search"

      # Save artifact ke GitHub
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: project/mlruns

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker Image from model registry
      - name: MLflow Build Docker Image
        run: |
          mlflow models build-docker \
            --model-uri "models:/water_potability/Production" \
            --name ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest