name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env: 
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"
      
      # Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.12"
          use-mamba: true
          activate-environment: "mlflow-env"
          environment-file: project/conda.yaml
          auto-activate-base: false
      
      # Clear Env
      - name: Clear MLflow Environment Vars
        run: |
          unset MLFLOW_RUN_ID || true
          unset MLFLOW_EXPERIMENT_ID || true
      
      # Run MLflow Training
      - name: Run MLflow Project
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate mlflow-env
          
          pip install -q dagshub 'mlflow>=2,<3' scikit-learn pandas numpy setuptools wheel

          mlflow run project -e train_tuning --env-manager=local -P experiment_name="Random Forest_Grid Search"

      # Save artifact ke GitHub
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns

      # Get latest model version
      - name: Get latest model version
        id: get_version
        shell: bash -l {0}
        run: |
          export MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }}
          export MLFLOW_TRACKING_USERNAME=${{ env.MLFLOW_TRACKING_USERNAME }}
          export MLFLOW_TRACKING_PASSWORD=${{ env.MLFLOW_TRACKING_PASSWORD }}
          
          LATEST_VERSION=$(python -c 'import os, mlflow; from mlflow.tracking import MlflowClient; os.environ["MLFLOW_TRACKING_USERNAME"]=os.environ["MLFLOW_TRACKING_USERNAME"]; os.environ["MLFLOW_TRACKING_PASSWORD"]=os.environ["MLFLOW_TRACKING_PASSWORD"]; mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"]); client = MlflowClient(); versions = client.search_model_versions("name=\"water_potability\""); version_nums = [int(v.version) for v in versions]; print(max(version_nums) if version_nums else 0)')
          
          echo "Model version found: $LATEST_VERSION"
          
          if [ "$LATEST_VERSION" -eq 0 ]; then
            echo "::error::ERROR: Model 'water_potability' ditemukan di UI, tetapi pencarian di CI gagal. Cek kembali kredensial atau nama model di Python script."
            exit 1 # Gagal jika tidak ada versi, karena model HARUS ADA.
          fi

          # Simpan ke Environment Variable GitHub Actions
          echo "MODEL_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker Image from model registry
      - name: MLflow Build Docker Image
        shell: bash -l {0}
        run: |
          echo "Building Docker for Model Version: ${{ env.MODEL_VERSION }}"
          
          mlflow models build-docker \
            --model-uri "models:/water_potability/${{ env.MODEL_VERSION }}" \
            --name ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest