name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

env:
  CSV_URL: "./project/water_potability_preprocessing.csv"
  TARGET_VAR: "Potability"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"

      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagshub "mlflow>=2,<3" pandas numpy scikit-learn
          pip install -r requirements.txt
      
      # Run Training
      - name: Run training script
        id: train_model
        run: |
          python modelling_tuning.py | tee output.log

          # Ambil BEST_MODEL_URI dari output
          BEST_URI=$(grep "BEST_MODEL_URI" output.log | awk '{print $2}')
          echo "MODEL_URI=$BEST_URI" >> $GITHUB_ENV
          echo "Model URI: $BEST_URI"
     
  docker:
    needs: train
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Download best model from DagsHub
        run: |
          mkdir -p model
          mlflow artifacts download \
            --artifact-uri ${{ env.MODEL_URI }} \
            --dst-path model/

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/potability-model:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/potability-model:latest
